spring:
  datasource:
    url: jdbc:postgresql://ec2-3-230-61-252.compute-1.amazonaws.com:5432/dfhf1tpdav59fm
    username: lfslyvianzvsdh
    password: 41101cc4bdde1cd892744f3502bbf41ec4331d5a4cf67e81b7fdbe425b793836
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB
  kafka:
    bootstrap-servers: dory-01.srvs.cloudkafka.com:9094,dory-02.srvs.cloudkafka.com:9094,dory-03.srvs.cloudkafka.com:9094
    topic: gj6u8n8t-article
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="gj6u8n8t" password="QJXrSTxS6DK4CXQVFndyYtIz8k7A-Q0c";
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: gj6u8n8t-consumers
      auto-offset-reset: latest
      properties:
        spring:
          json:
            trusted:
              packages: com.eden.springgallery.viewmodel
cloudinary:
  name: hox4mdapl
  key: 946349288714149
  secret: euAgCp2RVrflzzmyiK7z1O07Zsc
logging:
  level:
    root: INFO
